language: ruby
rvm:
  - 2.4.4
  - 2.5.5
  - 2.6.2
script: bundle exec rspec
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
matrix:
  exclude:
    - rvm: 2.5.5
      gemfile: gemfiles/rails_4.2.gemfile
