language: ruby
rvm:
  - 2.2.9
  - 2.3.7
  - 2.4.4
  - 2.5.1
script: bundle exec rspec
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
